version: '3'
services:
  account-service-integration:
    build:
      context: ..
      target: build
    image: account-service-integration
    ports:
      - 3001:3001
    env_file:
      - .env.integration
    depends_on:
      - postgres-integration
    volumes:
      - .:/src
    command:
      - npm
      - run
      - integration

  postgres-integration:
    image: postgres
    hostname: postgres-integration
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: integration
      POSTGRES_PASSWORD: integration
      POSTGRES_DB: account-service-integration
